version: "2"
services:
  metadata:
    build: .
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      # REQUIRED
      - 'AWS_ACCESS_KEY_ID=...'
      - 'AWS_SECRET_ACCESS_KEY=...'
      # OPTIONAL
      #- 'DEFAULT_IAM_ROLE=...'
    networks:
      metadata:
        ipv4_address: 169.254.169.254
networks:
  metadata:
    name: ec2_metadata
    external: true
