version: '3.7'
services:
  metadata:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws:/root/.aws
    env_file:
      - .env
    networks:
      metadata:
        ipv4_address: 169.254.169.254
  test_app:
    build:
      context: .
      target: test
    env_file:
      - .env
    depends_on:
      - metadata
    networks:
      - metadata
    command: curl http://169.254.169.254/latest/meta-data/iam/security-credentials/dev
networks:
  metadata:
    name: ec2_metadata
    external: true
